trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: Build
  jobs:
    - job: firstjob
      steps:
      - bash: echo Build First Job
    - job: SecondJob
      steps:
      - bash: echo Build Second Job
- stage: DevDeploy
  dependsOn: Build
  jobs:
    - job: DevFirst
      steps:
      - bash: echo Dev First Job
    - job: DevSecond
      steps:
      - bash: echo Dev Second Job
- stage: QADeploy
  dependsOn: Build
  jobs:
    - job: QAJob
      steps:
      - bash: echo QA First Job
- stage: ProdDeploy
  dependsOn:
  - DevDeploy
  - QADeploy
  jobs:
    - job: ProductionsJob
      steps:
      - bash: echo Production First Job